### ISSUE TITLE
sponge.pl Dosen't work

### ISSUE THREAD

**Issue by spongecattle** [spongeGene/BukkitKit#1]
File(s) affected:
sponge.pl
How to fix:
Fix the coding inside the file(s) listed above

**Comment by spongeGene** [comment]
Closed for reason:
The code works 100% well

**Comment by spongecattle** [comment]
Well that is unusual I saw a bug

**Comment by spongeGene** [comment]
Unusual I didn't see a bug!

**Comment by spongeGene** [comment]
Well if I never saw a bug then this is not valid
